eb setenv JWT_SECRET=$JWT_SECRET
eb PORT=$PORT POSTGRES_DB=$POSTGRES_DB
eb POSTGRES_HOST=$POSTGRES_HOST 
eb POSTGRES_PASSWORD=$POSTGRES_PASSWORD
eb POSTGRES_USERNAME=$POSTGRES_USERNAME 
eb AWS_REGION=$AWS_REGION