eb setenv JWT_SECRET=$JWT_SECRET
eb setenv PORT=$PORT POSTGRES_DB=$POSTGRES_DB
eb setenv POSTGRES_HOST=$POSTGRES_HOST 
eb setenv POSTGRES_PASSWORD=$POSTGRES_PASSWORD
eb setenv POSTGRES_USERNAME=$POSTGRES_USERNAME 
eb setenv AWS_REGION=$AWS_REGION